export const UserRoles = {
  partOf: {
    author: true,
    candidate: false,
    instructor: true,
    seller: false,
    lancer: false,
    client: false,
    organizer: false,
    host: false,
    expert: true,
    sponsor: true,
    customer: true,
  },
};

export const partOf = {
  author: UserRoles.partOf.author,
  candidate: UserRoles.partOf.candidate,
  instructor: UserRoles.partOf.instructor,
  seller: UserRoles.partOf.seller,
  lancer: UserRoles.partOf.lancer,
  client: UserRoles.partOf.client,
  organizer: UserRoles.partOf.organizer,
  host: UserRoles.partOf.host,
  expert: UserRoles.partOf.expert,
  sponsor: UserRoles.partOf.sponsor,
  customer: UserRoles.partOf.customer,
};

export const categories = [
  {
    value: "category1",
    label: "Category1",
  },
  {
    value: "category2",
    label: "Category2",
  },
  {
    value: "category3",
    label: "Category3",
  },
  {
    value: "category4",
    label: "Category4",
  },
  {
    value: "category5",
    label: "Category5",
  },
];

export const images = [
  "/images/FarmPicVet.png",
  "/images/PuppyPic.png",
  "/images/PuppyPic2.png",
  "/images/VetSurgerySignPic.png",
  "/images/FarmPicVet.png",
  "/images/PuppyPic.png",
  "/images/PuppyPic2.png",
  "/images/VetSurgerySignPic.png",
  "/images/FarmPicVet.png",
  "/images/PuppyPic.png",
  "/images/PuppyPic2.png",
  "/images/VetSurgerySignPic.png",
  "/images/FarmPicVet.png",
  "/images/PuppyPic.png",
  "/images/PuppyPic2.png",
  "/images/VetSurgerySignPic.png",
  "/images/FarmPicVet.png",
  "/images/PuppyPic.png",
  "/images/PuppyPic2.png",
  "/images/VetSurgerySignPic.png",
  "/images/FarmPicVet.png",
  "/images/PuppyPic.png",
  "/images/PuppyPic2.png",
  "/images/VetSurgerySignPic.png",
];

export const vGuideUserData = {
  sales: 20000,
  userName: "Dr. Ahmed Hassan",
  userTitle: "Large Animals Consultant at Majestic Farm",
  earnings: 20000,
  investments: 7500,
  endorsements: 44,
  points: 3500,
  likes: 9000,
  shares: 1100,
  connections: 300,
  followers: 5600,
  members: 10200,
  subscribers: 200,
  customers: 43300,
  assets: 3500,
  currency: "$",
  rating: 2.7,
  ratingPoints: 1000000,
  isFeatured: "featured",
  profileType: "Personal",
  rank: "standardSilver",
  isEmailVerified: true,
  isPhoneVerified: true,
  isAgreementVerified: false,
  isIdVerified: true,
  vUserInfoData: {
    id: "MBR-756",
    gender: "Male",
    country: "Egypt",
    location: "UAE - Dubai", // location and location Type
    time: "01:00 PM",
    calendar: "15-Sep-2022 02:45 PM",
    lastSeen: "11-Nov-2022 09:45 PM",
  },
};

export const vBlogUserData = {
  posts: 1000,
  likes: 9000,
  shares: 1100,
  ratingPoints: 1200,
  rating: 4.7,
  userName: "Dr. Ahmed Hassan",
  userTitle: "Demo Profile Banner V-Blog Banner",
  points: 1000,
  endorsements: 1548,
  isFeatured: "featured",
  rank: "standardPlatinum",
  dataType: "blog",
};

export const vAuthorUserData = {
  posts: 350,
  socialPages: 4,
  socialGroups: 5,
  followers: 3200,
  members: 9700,
  likes: 4500,
  shares: 1100,
  ratingPoints: 1200,
  rating: 3.7,
  userName: "Dr. Ahmed Hassan",
  userTitle: "Demo Profile Banner V-Author Banner",
  isFeatured: "featured",
  rank: "standardGold",
  dataType: "author",
  points: 100,
  endorsements: 1000,
};

export const vTubeUserData = {
  channels: 4,
  videos: 1000,
  subscribers: 20000,
  views: 256000,
  likes: 4500,
  shares: 900,
  ratingPoints: 1200,
  rating: 5,
  userName: "Dr. Ahmed Hassan",
  userTitle: "Demo Profile Banner V-Tube Banner",
  points: 678,
  endorsements: 547,
  isFeatured: "featured",
  rank: "ambassadorSilver",
  dataType: "tube",
};

export const vJobUserData = {
  experience: 17,
  salary: 2500,
  likes: 4500,
  shares: 900,
  userName: "Dr. Ahmed Hassan",
  userTitle: "Demo Profile Banner V-Job Banner",
  points: 678,
  endorsements: 547,
  isFeatured: "featured",
  rank: "ambassadorSilver",
  dataType: "jobs",
  isOpenToWork: "Open To Work",
};

export const vLanceUserData = {
  services: 20,
  sales: 7500,
  orders: 1000,
  customers: 525,
  successRate: 100,
  likes: 4500,
  shares: 900,
  ratingPoints: 1200,
  rating: 4.7,
  userName: "Dr. Ahmed Hassan",
  userTitle: "Demo Profile Banner V-Lance Banner",
  points: 678,
  endorsements: 547,
  isFeatured: "featured",
  rank: "vendorSilver",
  dataType: "lance",
};

export const vCollegeUserData = {
  courses: 4,
  sales: 1000,
  orders: 1000,
  customers: 1000,
  likes: 4500,
  shares: 900,
  ratingPoints: 1200,
  rating: 4.7,
};

export const vMarketUserData = {
  stores: 4,
  products: 1000,
  sales: 1000,
  orders: 1000,
  customers: 1000,
  likes: 4500,
  shares: 900,
  ratingPoints: 900,
  rating: 4.9,
};

export const vEventsUserData = {
  events: 20,
  sales: 7500,
  orders: 1000,
  customers: 525,
  likes: 4500,
  shares: 900,
  ratingPoints: 900,
  rating: 4.9,
};

export const vWebinarsUserData = {
  webinars: 20,
  sales: 7500,
  orders: 1000,
  customers: 525,
  likes: 4500,
  shares: 900,
  ratingPoints: 900,
  rating: 4.9,
};

export const vExpertsUserData = {
  consultations: 20,
  sales: 7500,
  orders: 1000,
  customers: 525,
  likes: 4500,
  shares: 900,
  ratingPoints: 900,
  rating: 4.9,
};

export const vMarketingSponsorUserData = {
  investments: 2200,
  sponsored: 10,
  orders: 50,
};

export const vMarketingUserData = {
  sponsorships: 15,
  sales: 2200,
  orders: 50,
  customers: 525,
  likes: 4500,
  shares: 900,
  ratingPoints: 900,
  rating: 4.9,
};

export const VAlertCenterData = {
  Notifications: {
    vVerse: [
      {
        id: 1,
        title: "Started to follow",
        user: "Ahmad Hassan",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 2,
        title: "Joined Your GroupName",
        user: "Jack",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 3,
        title: "Started to follow",
        user: "Dave",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 4,
        title: "Joined Your GroupName",
        user: "Jason",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 5,
        title: "Started to follow",
        user: "Jad",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 6,
        title: "Joined Your GroupName",
        user: "Makram",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 7,
        title: "Started to follow",
        user: "Sally",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 8,
        title: "Joined Your GroupName",
        user: "Nour",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 9,
        title: "Started to follow",
        user: "farah",
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 10,
        title: "Joined Your GroupName",
        user: "Jasmine",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 11,
        title: "Started to follow",
        user: "Ziad",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 12,
        title: "Joined Your GroupName",
        user: "Hassan",
        actions: ["viewReport"],
        date: "2023-04-05T12:50:00Z",
      },
    ],
    vGuide: [
      {
        id: 1,
        title: "Started to follow",
        user: "Ahmad Hassan",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 2,
        title: "Joined Your GroupName",
        user: "Jack",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 3,
        title: "Started to follow",
        user: "Dave",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 4,
        title: "Joined Your GroupName",
        user: "Jason",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 5,
        title: "Started to follow",
        user: "Jad",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 6,
        title: "Joined Your GroupName",
        user: "Makram",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 7,
        title: "Started to follow",
        user: "Sally",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 8,
        title: "Joined Your GroupName",
        user: "Nour",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 9,
        title: "Started to follow",
        user: "farah",
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 10,
        title: "Joined Your GroupName",
        user: "Jasmine",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 11,
        title: "Started to follow",
        user: "Ziad",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 12,
        title: "Joined Your GroupName",
        user: "Hassan",
        actions: ["viewReport"],
        date: "2023-04-05T12:50:00Z",
      },
    ],
    vBlog: [
      {
        id: 1,
        title: "Started to follow",
        user: "Ahmad Hassan",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 2,
        title: "Joined Your GroupName",
        user: "Jack",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 3,
        title: "Started to follow",
        user: "Dave",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 4,
        title: "Joined Your GroupName",
        user: "Jason",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 5,
        title: "Started to follow",
        user: "Jad",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 6,
        title: "Joined Your GroupName",
        user: "Makram",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 7,
        title: "Started to follow",
        user: "Sally",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 8,
        title: "Joined Your GroupName",
        user: "Nour",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 9,
        title: "Started to follow",
        user: "farah",
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 10,
        title: "Joined Your GroupName",
        user: "Jasmine",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 11,
        title: "Started to follow",
        user: "Ziad",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 12,
        title: "Joined Your GroupName",
        user: "Hassan",
        actions: ["viewReport"],
        date: "2023-04-05T12:50:00Z",
      },
    ],
    vNation: [
      {
        id: 1,
        title: "Started to follow",
        user: "Ahmad Hassan",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 2,
        title: "Joined Your GroupName",
        user: "Jack",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 3,
        title: "Started to follow",
        user: "Dave",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 4,
        title: "Joined Your GroupName",
        user: "Jason",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 5,
        title: "Started to follow",
        user: "Jad",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 6,
        title: "Joined Your GroupName",
        user: "Makram",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 7,
        title: "Started to follow",
        user: "Sally",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 8,
        title: "Joined Your GroupName",
        user: "Nour",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 9,
        title: "Started to follow",
        user: "farah",
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 10,
        title: "Joined Your GroupName",
        user: "Jasmine",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 11,
        title: "Started to follow",
        user: "Ziad",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 12,
        title: "Joined Your GroupName",
        user: "Hassan",
        actions: ["viewReport"],
        date: "2023-04-05T12:50:00Z",
      },
    ],
    vTube: [
      {
        id: 1,
        title: "Started to follow",
        user: "Ahmad Hassan",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 2,
        title: "Joined Your GroupName",
        user: "Jack",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 3,
        title: "Started to follow",
        user: "Dave",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 4,
        title: "Joined Your GroupName",
        user: "Jason",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 5,
        title: "Started to follow",
        user: "Jad",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 6,
        title: "Joined Your GroupName",
        user: "Makram",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 7,
        title: "Started to follow",
        user: "Sally",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 8,
        title: "Joined Your GroupName",
        user: "Nour",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 9,
        title: "Started to follow",
        user: "farah",
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 10,
        title: "Joined Your GroupName",
        user: "Jasmine",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 11,
        title: "Started to follow",
        user: "Ziad",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 12,
        title: "Joined Your GroupName",
        user: "Hassan",
        actions: ["viewReport"],
        date: "2023-04-05T12:50:00Z",
      },
    ],
    vJobs: [
      {
        id: 1,
        title: "Started to follow",
        user: "Ahmad Hassan",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 2,
        title: "Joined Your GroupName",
        user: "Jack",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 3,
        title: "Started to follow",
        user: "Dave",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 4,
        title: "Joined Your GroupName",
        user: "Jason",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 5,
        title: "Started to follow",
        user: "Jad",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 6,
        title: "Joined Your GroupName",
        user: "Makram",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 7,
        title: "Started to follow",
        user: "Sally",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 8,
        title: "Joined Your GroupName",
        user: "Nour",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 9,
        title: "Started to follow",
        user: "farah",
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 10,
        title: "Joined Your GroupName",
        user: "Jasmine",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 11,
        title: "Started to follow",
        user: "Ziad",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 12,
        title: "Joined Your GroupName",
        user: "Hassan",
        actions: ["viewReport"],
        date: "2023-04-05T12:50:00Z",
      },
    ],
    vLance: [
      {
        id: 1,
        title: "Started to follow",
        user: "Ahmad Hassan",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 2,
        title: "Joined Your GroupName",
        user: "Jack",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 3,
        title: "Started to follow",
        user: "Dave",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 4,
        title: "Joined Your GroupName",
        user: "Jason",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 5,
        title: "Started to follow",
        user: "Jad",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 6,
        title: "Joined Your GroupName",
        user: "Makram",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 7,
        title: "Started to follow",
        user: "Sally",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 8,
        title: "Joined Your GroupName",
        user: "Nour",

        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 9,
        title: "Started to follow",
        user: "farah",

        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 10,
        title: "Joined Your GroupName",
        user: "Jasmine",

        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 11,
        title: "Started to follow",
        user: "Ziad",

        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 12,
        title: "Joined Your GroupName",
        user: "Hassan",
        actions: ["viewReport"],
        date: "2023-04-05T12:50:00Z",
      },
    ],
    vCollege: [
      {
        id: 1,
        title: "Started to follow",
        user: "Ahmad Hassan",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 2,
        title: "Joined Your GroupName",
        user: "Jack",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 3,
        title: "Started to follow",
        user: "Dave",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 4,
        title: "Joined Your GroupName",
        user: "Jason",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 5,
        title: "Started to follow",
        user: "Jad",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 6,
        title: "Joined Your GroupName",
        user: "Makram",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 7,
        title: "Started to follow",
        user: "Sally",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 8,
        title: "Joined Your GroupName",
        user: "Nour",

        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 9,
        title: "Started to follow",
        user: "farah",

        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 10,
        title: "Joined Your GroupName",
        user: "Jasmine",

        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 11,
        title: "Started to follow",
        user: "Ziad",

        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 12,
        title: "Joined Your GroupName",
        user: "Hassan",
        actions: ["viewReport"],
        date: "2023-04-05T12:50:00Z",
      },
    ],
    vMarket: [
      {
        id: 1,
        title: "Started to follow",
        user: "Ahmad Hassan",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 2,
        title: "Joined Your GroupName",
        user: "Jack",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 3,
        title: "Started to follow",
        user: "Dave",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 4,
        title: "Joined Your GroupName",
        user: "Jason",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 5,
        title: "Started to follow",
        user: "Jad",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 6,
        title: "Joined Your GroupName",
        user: "Makram",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 7,
        title: "Started to follow",
        user: "Sally",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 8,
        title: "Joined Your GroupName",
        user: "Nour",

        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 9,
        title: "Started to follow",
        user: "farah",

        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 10,
        title: "Joined Your GroupName",
        user: "Jasmine",

        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 11,
        title: "Started to follow",
        user: "Ziad",

        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 12,
        title: "Joined Your GroupName",
        user: "Hassan",
        actions: ["viewReport"],
        date: "2023-04-05T12:50:00Z",
      },
    ],
    vEvents: [
      {
        id: 1,
        title: "Started to follow",
        user: "Ahmad Hassan",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 2,
        title: "Joined Your GroupName",
        user: "Jack",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 3,
        title: "Started to follow",
        user: "Dave",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 4,
        title: "Joined Your GroupName",
        user: "Jason",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 5,
        title: "Started to follow",
        user: "Jad",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 6,
        title: "Joined Your GroupName",
        user: "Makram",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 7,
        title: "Started to follow",
        user: "Sally",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 8,
        title: "Joined Your GroupName",
        user: "Nour",

        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 9,
        title: "Started to follow",
        user: "farah",

        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 10,
        title: "Joined Your GroupName",
        user: "Jasmine",

        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 11,
        title: "Started to follow",
        user: "Ziad",

        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 12,
        title: "Joined Your GroupName",
        user: "Hassan",
        actions: ["viewReport"],
        date: "2023-04-05T12:50:00Z",
      },
    ],
    vWebinars: [
      {
        id: 1,
        title: "Started to follow",
        user: "Ahmad Hassan",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 2,
        title: "Joined Your GroupName",
        user: "Jack",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 3,
        title: "Started to follow",
        user: "Dave",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 4,
        title: "Joined Your GroupName",
        user: "Jason",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 5,
        title: "Started to follow",
        user: "Jad",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 6,
        title: "Joined Your GroupName",
        user: "Makram",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 7,
        title: "Started to follow",
        user: "Sally",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 8,
        title: "Joined Your GroupName",
        user: "Nour",

        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 9,
        title: "Started to follow",
        user: "farah",

        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 10,
        title: "Joined Your GroupName",
        user: "Jasmine",

        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 11,
        title: "Started to follow",
        user: "Ziad",

        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 12,
        title: "Joined Your GroupName",
        user: "Hassan",
        actions: ["viewReport"],
        date: "2023-04-05T12:50:00Z",
      },
    ],
    vExperts: [
      {
        id: 1,
        title: "Started to follow",
        user: "Ahmad Hassan",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 2,
        title: "Joined Your GroupName",
        user: "Jack",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 3,
        title: "Started to follow",
        user: "Dave",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 4,
        title: "Joined Your GroupName",
        user: "Jason",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 5,
        title: "Started to follow",
        user: "Jad",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 6,
        title: "Joined Your GroupName",
        user: "Makram",
        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 7,
        title: "Started to follow",
        user: "Sally",
        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 8,
        title: "Joined Your GroupName",
        user: "Nour",

        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 9,
        title: "Started to follow",
        user: "farah",

        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 10,
        title: "Joined Your GroupName",
        user: "Jasmine",

        date: "2023-04-05T12:50:00Z",
      },
      {
        id: 11,
        title: "Started to follow",
        user: "Ziad",

        actions: ["accept", "decline"],
        date: "2023-04-05T11:00:00Z",
      },
      {
        id: 12,
        title: "Joined Your GroupName",
        user: "Hassan",
        actions: ["viewReport"],
        date: "2023-04-05T12:50:00Z",
      },
    ],
  },
  Messages: [
    {
      id: 1,
      user: "V-Verse",
      title:
        "Sent You a Message, demo vv-verse messaging notification alert center.",
      fromPillar: "vVerse",
      date: "2023-04-05T12:50:00Z",
    },
    {
      id: 2,
      user: "V-Verse",
      title:
        "Sent You a Message, demo vv-verse messaging notification alert center.",
      fromPillar: "vGuide",
      date: "2023-04-05T12:50:00Z",
    },
    {
      id: 3,
      user: "V-Verse",
      title:
        "Sent You a Message, demo vv-verse messaging notification alert center.",
      fromPillar: "vBlog",
      date: "2023-04-05T12:50:00Z",
    },
    {
      id: 4,
      user: "V-Verse",
      title:
        "Sent You a Message, demo vv-verse messaging notification alert center.",
      fromPillar: "vNation",
      date: "2023-04-05T12:50:00Z",
    },
    {
      id: 5,
      user: "V-Verse",
      title:
        "Sent You a Message, demo vv-verse messaging notification alert center.",
      fromPillar: "vTube",
      date: "2023-04-05T12:50:00Z",
    },
    {
      id: 6,
      user: "V-Verse",
      title:
        "Sent You a Message, demo vv-verse messaging notification alert center.",
      fromPillar: "vJobs",
      date: "2023-04-05T12:50:00Z",
    },
    {
      id: 7,
      user: "V-Verse",
      title:
        "Sent You a Message, demo vv-verse messaging notification alert center.",
      fromPillar: "vLance",
      date: "2023-04-05T12:50:00Z",
    },
    {
      id: 8,
      user: "V-Verse",
      title:
        "Sent You a Message, demo vv-verse messaging notification alert center.",
      fromPillar: "vWebinars",
      date: "2023-04-05T12:50:00Z",
    },
    {
      id: 9,
      user: "V-Verse",
      title:
        "Sent You a Message, demo vv-verse messaging notification alert center.",
      fromPillar: "vEvents",
      date: "2023-04-05T12:50:00Z",
    },
    {
      id: 10,
      user: "V-Verse",
      title:
        "Sent You a Message, demo vv-verse messaging notification alert center.",
      fromPillar: "vExperts",
      date: "2023-04-05T12:50:00Z",
    },
  ],
  Emails: [
    {
      id: 1,
      senderName: "John Johnny Doe",
      title: "Emailing you about the Vverse Demo",
      subTitle:
        "lorem Hey John, wellish laminable inuent popshop catalyte prismatic guevni.",
      message:
        "Hey John, this is a test email, for the Vverse demo, let me know if you have any questions.",
      date: "2023-04-05T12:50:00Z",
      numberOfMessages: 5,
      type: "vVerse",
    },
    {
      id: 2,
      senderName: "John Johnny Doe",
      title: "Emailing you about the Vverse Demo",
      subTitle:
        "lorem Hey John, wellish laminable inuent popshop catalyte prismatic guevni.",
      message:
        "Hey John, this is a test email, for the Vverse demo, let me know if you have any questions.",
      date: "2023-04-05T12:50:00Z",
      numberOfMessages: 6,
      type: "Personal",
    },
    {
      id: 3,
      senderName: "John Johnny Doe",
      title: "Emailing you about the Vverse Demo",
      subTitle:
        "lorem Hey John, wellish laminable inuent popshop catalyte prismatic guevni.",
      message:
        "Hey John, this is a test email, for the Vverse demo, let me know if you have any questions.",
      date: "2023-04-05T12:50:00Z",
      numberOfMessages: 9,
      type: "Business",
    },
  ],
  Planner: {
    onlineMeetings: [
      {
        id: 1,
        title: "Meeting With Developers",
        startDate: "2023-04-05T11:00:00Z",
        endDate: "2023-04-05T11:30:00Z",
        status: "High",
        meetingType: "Online Meetings",
        matters: "Personal",
      },
      {
        id: 2,
        title: "Meeting With Developers",
        startDate: "2023-04-05T11:00:00Z",
        endDate: "2023-04-05T11:30:00Z",
        status: "Medium",
        meetingType: "Online Meetings",
        matters: "Business",
      },
      {
        id: 3,
        title: "Meeting With Developers",
        startDate: "2023-04-05T11:00:00Z",
        endDate: "2023-04-05T11:30:00Z",
        status: "Low",
        meetingType: "Online Meetings",
        matters: "Personal",
      },
    ],
    offlineMeetings: [
      {
        id: 1,
        title: "Meeting With Developers",
        startDate: "2023-04-05T11:00:00Z",
        endDate: "2023-04-05T11:30:00Z",
        status: "High",
        meetingType: "Offline Meetings",
        matters: "Personal",
      },
      {
        id: 2,
        title: "Meeting With Developers",
        startDate: "2023-04-05T11:00:00Z",
        endDate: "2023-04-05T11:30:00Z",
        status: "Medium",
        meetingType: "Offline Meetings",
        matters: "Business",
      },
      {
        id: 3,
        title: "Meeting With Developers",
        startDate: "2023-04-05T11:00:00Z",
        endDate: "2023-04-05T11:30:00Z",
        status: "Low",
        meetingType: "Offline Meetings",
        matters: "Personal",
      },
      {
        id: 4,
        title: "Meeting With Developers",
        startDate: "2023-04-05T11:00:00Z",
        endDate: "2023-04-05T11:30:00Z",
        status: "Low",
        meetingType: "Offline Meetings",
        matters: "Personal",
      },
    ],
    webinarMeetings: [
      {
        id: 1,
        title: "Meeting With Developers",
        startDate: "2023-04-05T11:00:00Z",
        endDate: "2023-04-05T11:30:00Z",
        status: "High",
        meetingType: "Online Webinars",
        matters: "Personal",
      },
      {
        id: 2,
        title: "Meeting With Developers",
        startDate: "2023-04-05T11:00:00Z",
        endDate: "2023-04-05T11:30:00Z",
        status: "Medium",
        meetingType: "Online Webinars",
        matters: "Business",
      },
      {
        id: 3,
        title: "Meeting With Developers",
        startDate: "2023-04-05T11:00:00Z",
        endDate: "2023-04-05T11:30:00Z",
        status: "Low",
        meetingType: "Online Webinars",
        matters: "Personal",
      },
      {
        id: 4,
        title: "Meeting With Developers",
        startDate: "2023-04-05T11:00:00Z",
        endDate: "2023-04-05T11:30:00Z",
        status: "Low",
        meetingType: "Online Webinars",
        matters: "Personal",
      },
      {
        id: 5,
        title: "Meeting With Developers",
        startDate: "2023-04-05T11:00:00Z",
        endDate: "2023-04-05T11:30:00Z",
        status: "Low",
        meetingType: "Online Webinars",
        matters: "Personal",
      },
    ],
    eventMeetings: [
      {
        id: 1,
        title: "Meeting With Developers",
        startDate: "2023-04-05T11:00:00Z",
        endDate: "2023-04-05T11:30:00Z",
        status: "High",
        meetingType: "Offline Events",
        matters: "Personal",
      },
      {
        id: 2,
        title: "Meeting With Developers",
        startDate: "2023-04-05T11:00:00Z",
        endDate: "2023-04-05T11:30:00Z",
        status: "Medium",
        meetingType: "Offline Events",
        matters: "Business",
      },
      {
        id: 3,
        title: "Meeting With Developers",
        startDate: "2023-04-05T11:00:00Z",
        endDate: "2023-04-05T11:30:00Z",
        status: "Low",
        meetingType: "Offline Events",
        matters: "Personal",
      },
      {
        id: 4,
        title: "Meeting With Developers",
        startDate: "2023-04-05T11:00:00Z",
        endDate: "2023-04-05T11:30:00Z",
        status: "Low",
        meetingType: "Offline Events",
        matters: "Personal",
      },
      {
        id: 5,
        title: "Meeting With Developers",
        startDate: "2023-04-05T11:00:00Z",
        endDate: "2023-04-05T11:30:00Z",
        status: "Low",
        meetingType: "Offline Events",
        matters: "Personal",
      },
      {
        id: 6,
        title: "Meeting With Developers",
        startDate: "2023-04-05T11:00:00Z",
        endDate: "2023-04-05T11:30:00Z",
        status: "Low",
        meetingType: "Offline Events",
        matters: "Personal",
      },
    ],
    todos: [
      {
        id: 1,
        title: "Meeting With Developers",
        startDate: "2023-04-05T11:00:00Z",
        endDate: "2023-04-05T11:30:00Z",
        status: "High",
        meetingType: "Offline Events",
        matters: "Personal",
      },
      {
        id: 2,
        title: "Meeting With Developers",
        startDate: "2023-04-05T11:00:00Z",
        endDate: "2023-04-05T11:30:00Z",
        status: "Medium",
        meetingType: "Offline Events",
        matters: "Business",
      },
    ],
  },
  News: [
    {
      id: 1,
      title:
        "Cillum adipisicing velit ea nostrud commodo excepteur aliquip nisi in eiusmod reprehenderit.",
      date: "2023-04-05T11:00:00Z",
    },
    {
      id: 2,
      title:
        "Cillum adipisicing velit ea nostrud commodo excepteur aliquip nisi in eiusmod reprehenderit.",
      date: "2023-04-05T11:00:00Z",
    },
    {
      id: 3,
      title:
        "Cillum adipisicing velit ea nostrud commodo excepteur aliquip nisi in eiusmod reprehenderit.",
      date: "2023-04-05T11:00:00Z",
    },
    {
      id: 4,
      title:
        "Cillum adipisicing velit ea nostrud commodo excepteur aliquip nisi in eiusmod reprehenderit.",
      date: "2023-04-05T11:00:00Z",
    },
    {
      id: 5,
      title:
        "Cillum adipisicing velit ea nostrud commodo excepteur aliquip nisi in eiusmod reprehenderit.",
      date: "2023-04-05T11:00:00Z",
    },
    {
      id: 6,
      title:
        "Cillum adipisicing velit ea nostrud commodo excepteur aliquip nisi in eiusmod reprehenderit.",
      date: "2023-04-05T11:00:00Z",
    },
    {
      id: 7,
      title:
        "Cillum adipisicing velit ea nostrud commodo excepteur aliquip nisi in eiusmod reprehenderit.",
      date: "2023-04-05T11:00:00Z",
    },
    {
      id: 8,
      title:
        "Cillum adipisicing velit ea nostrud commodo excepteur aliquip nisi in eiusmod reprehenderit.",
      date: "2023-04-05T11:00:00Z",
    },
    {
      id: 9,
      title:
        "Cillum adipisicing velit ea nostrud commodo excepteur aliquip nisi in eiusmod reprehenderit.",
      date: "2023-04-05T11:00:00Z",
    },
    {
      id: 10,
      title:
        "Cillum adipisicing velit ea nostrud commodo excepteur aliquip nisi in eiusmod reprehenderit.",
      date: "2023-04-05T11:00:00Z",
    },
  ],
};

export const vAssetBlogData = [
  {
    id: 1,
    assetId: "ASS-BPO-112",
    type: "public",
    userName: "Dr. Ahmad Hassan",
    title:
      "Cillum adipisicing velit ea nostrud commodo excepteur aliquip nisi in eiusmod reprehenderit.",
    dateStart: "23-Jan-2021 12:30 AM",
    dateEnd: "15-Sep-2022 11:30 AM",
    comments: 10200,
    likes: 110000,
    shares: 32000,
    rating: 4.8,
    ratingPoints: 2000,
    isFeatured: "featured",
    imageUrl: "/images/CowImageArticleBanner.png",
  },
  {
    id: 2,
    assetId: "ASS-BPO-113",
    userName: "Dr. John Doe",
    title:
      "Cillum adipisicing velit ea nostrud commodo excepteur aliquip nisi in eiusmod reprehenderit.",
    dateStart: "23-Jan-2021 12:30 AM",
    dateEnd: "15-Sep-2022 11:30 AM",
    comments: 10200,
    likes: 110000,
    shares: 32000,
    rating: 4.8,
    ratingPoints: 2000,
    isFeatured: "featured",
    imageUrl: "/images/article-camels-desert.png",
    type: "private",
  },
];

export const vAssetNationData = [
  {
    id: 1,
    assetId: "ASS-SGR-112",
    userName: "Dr. Ahmad Hassan",
    title: "Dr. Ahmad Hassan Official Social Page",
    date: "22-Sep-2023 7:30 PM",
    posts: 102,
    likes: 110000,
    shares: 32000,
    rating: 4.8,
    ratingPoints: 2000,
    followers: 2200,
    isFeatured: "featured",
    imageUrl: "/images/CowImageArticleBanner.png",
    type: "public",
  },
  {
    id: 2,
    assetId: "ASS-SGR-113",
    userName: "Dr. John Doe",
    title: "Dr. John Doe's Official Social Page",
    date: "19-Nov-2025 1:30 AM",
    posts: 112,
    likes: 110000,
    shares: 32000,
    rating: 4.8,
    ratingPoints: 2000,
    followers: 2200,
    isFeatured: "featured",
    imageUrl: "/images/article-camels-desert.png",
    type: "private",
  },
];

export const vAssetTubeData = [
  {
    id: 1,
    assetId: "ASS-CNL-112",
    userName: "Dr. Ahmad Hassan",
    title: "Dr. Ahmad Hassan Official Social Page",
    date: "22-Sep-2023 7:30 PM",
    views: 120000,
    subscribers: 300,
    channelFollowers: 2200,
    isFeatured: "featured",
    likes: 110000,
    shares: 32000,
    rating: 4.8,
    ratingPoints: 2000,
    imageUrl: "/images/CowImageArticleBanner.png",
    type: "public",
  },
  {
    id: 2,
    assetId: "ASS-CNL-113",
    userName: "Dr. John Doe",
    title: "Dr. John Doe's Official Social Page",
    date: "19-Nov-2025 1:30 AM",
    views: 1220,
    subscribers: 300,
    channelFollowers: 2200,
    isFeatured: "featured",
    likes: 110000,
    shares: 32000,
    rating: 4.8,
    ratingPoints: 2000,
    imageUrl: "/images/CowTaggedImage.png",
    type: "private",
  },
];
// change to lance
export const vAssetLanceServiceData = [
  {
    id: 1,
    assetId: "ASS-SRV-122",
    title:
      "Lance Service Page for sale, services for sale. V-Verse Lancer Asset.",
    type: "public",
    userName: "Dr. Ahmad Hassan",
    date: "19-Nov-2025 1:30 AM",
    sales: 22200,
    orders: 1200,
    customers: 1200,
    likes: 110000,
    shares: 32000,
    rating: 4.8,
    ratingPoints: 2000,
    isFeatured: "featured",
    isExclusive: "exclusive",
    price: 40,
    deliveryTime: 72,
    imageUrl: "/images/article-laptop-typing.png",
  },
  {
    id: 2,
    assetId: "ASS-SRV-123",
    title:
      "Lance Service Page for sale, services for sale. V-Verse Lancer Asset.",
    type: "private",
    userName: "Dr. Ahmad Hassan",
    date: "22-Nov-2025 1:30 AM",
    sales: 2220000,
    orders: 12000,
    customers: 22000,
    likes: 1100000,
    shares: 320000,
    rating: 4.8,
    ratingPoints: 1100000,
    isFeatured: "featured",
    isExclusive: "exclusive",
    price: 40,
    deliveryTime: 72,
    imageUrl: "/images/article-laptop-typing.png",
  },
];

export const vAssetLanceProjectData = [
  {
    id: 1,
    assetId: "ASS-PRJ-101",
    type: "public",
    title:
      "Lance Project Asset Banner Title, longer than 2 lines, lorem epsom, Est adipisicing qui duis velit consectetur amet cillum ea amet. Ut proident labore id dolore aliqua commodo ex incididunt ut.",
    userName: "Dr. Ahmad Hassan",
    date: "19-Nov-2025 1:30 AM",
    collaborators: 120,
    likes: 11000,
    shares: 3200,
    isHiring: "hiring",
    deliveryTime: 24,
    workType: "onsite",
    expertise: "beginner",
    paymentType: "fixed",
    budget: "725",
    imageUrl: "/images/article-coder-coding.png",
  },
  {
    id: 2,
    assetId: "ASS-PRJ-102",
    type: "private",
    title:
      "Lance Project Asset Banner Title, longer than 2 lines, lorem epsom, Ea tempor esse ut Lorem officia. Ullamco ut incididunt velit consectetur velit velit dolor duis elit non elit non aliquip id.",
    userName: "Dr. Ahmad Hassan",
    date: "30-Nov-2030 1:30 AM",
    collaborators: 12000,
    likes: 11000000,
    shares: 3200000,
    isHiring: "hiring",
    deliveryTime: 24,
    workType: "remote",
    expertise: "intermediate",
    paymentType: "fixed",
    budget: "825",
    imageUrl: "/images/article-horses-riding.png",
  },
  {
    id: 3,
    assetId: "ASS-PRJ-103",
    type: "private",
    title:
      "Lance Project Asset Banner Title, longer than 2 lines, lorem epsom, Ipsum deserunt id labore deserunt. Laborum tempor sit dolore exercitation ipsum do dolore non ipsum ea fugiat dolor veniam laboris.",
    userName: "Dr. Ahmad Hassan",
    date: "30-Feb-2030 6:30 AM",
    collaborators: 12000,
    likes: 11000000,
    shares: 3200000,
    // isHiring: "hiring",
    deliveryTime: 24,
    workType: "hybrid",
    expertise: "advanced",
    paymentType: "fixed",
    budget: "1100",
    imageUrl: "/images/article-camels-desert.png",
  },
];

export const vAssetCollegeData = [
  {
    id: 1,
    assetId: "ASS-CRS-14",
    type: "public",
    title: "V-College Asset Banner Data",
    userName: "Dr. Ahmad Hassan",
    date: "19-Nov-2025 1:30 AM",
    sales: 77000,
    orders: 1200,
    customers: 2200,
    likes: 1100,
    shares: 320,
    rating: 4.8,
    ratingPoints: 1100000,
    isFeatured: "featured",
    isExclusive: "exclusive",
    price: 100,
    paymentType: "paid",
    bargain: "discount",
    discountPercentage: 25,
    expertise: "intermediate",
    imageUrl: "/images/article-laptop-typing.png",
  },
  {
    id: 2,
    assetId: "ASS-CRS-15",
    type: "public",
    userName: "Dr. Ahmad Hassan",
    date: "19-Nov-2025 1:30 AM",
    sales: 77000,
    orders: 1200,
    customers: 2200,
    likes: 1100,
    shares: 320,
    rating: 4.8,
    ratingPoints: 1100000,
    isFeatured: "featured",
    isExclusive: "exclusive",
    price: 100,
    paymentType: "paid",
    bargain: "regular",
    // discountPercentage: 25,
    expertise: "intermediate",
    imageUrl: "/images/article-horse-back-riding.png",
  },
];

export const vAssetStoreData = [
  {
    id: 1,
    assetId: "ASS-STR-8990",
    type: "public",
    userName: "Dr. Ahmad Hassan",
    date: "19-Nov-2025 1:30 AM",
    products: 1200,
    sales: 22000,
    orders: 1200,
    customers: 1200,
    likes: 1100,
    shares: 320,
    rating: 4.8,
    ratingPoints: 33,
    isFeatured: "featured",
    imageUrl: "/images/article-store-banner.png",
  },
  {
    id: 2,
    assetId: "ASS-STR-8991",
    type: "private",
    userName: "Dr. Ahmad Hassan",
    date: "19-Nov-2025 1:30 AM",
    products: 1200,
    sales: 22000,
    orders: 1200,
    customers: 1200,
    likes: 1100,
    shares: 320,
    rating: 4.8,
    ratingPoints: 33,
    isFeatured: "featured",
    imageUrl: "/images/article-store-banner.png",
  },
];

export const vAssetProductBanner = [
  {
    id: 1,
    assetId: "ASS-PRD-8990",
    type: "public",
    userName: "Dr. Ahmad Hassan",
    date: "19-Nov-2025 1:30 AM",
    sales: 22000,
    orders: 1200,
    customers: 1200,
    likes: 1100,
    shares: 320,
    rating: 4.8,
    ratingPoints: 33,
    isFeatured: "featured",
    isExclusive: "exclusive",
    price: 100,
    paymentType: "paid",
    bargain: "discount",
    discountPercentage: 25,
    stock: "In Stock",
    imageUrl: "/images/article-dog-food.png",
  },
  {
    id: 2,
    assetId: "ASS-PRD-8992",
    type: "private",
    userName: "Dr. Ahmad Hassan",
    date: "19-Nov-2025 5:30 AM",
    sales: 22000,
    orders: 1200,
    customers: 1200,
    likes: 1100,
    shares: 320,
    rating: 4.8,
    ratingPoints: 33,
    // isFeatured: "featured",
    isExclusive: "exclusive",
    price: 100,
    paymentType: "paid",
    // bargain: "discount",
    // discountPercentage: 25,
    stock: "Out of Stock",
    imageUrl: "/images/article-store-banner.png",
  },
];

export const vAssetEbookData = [
  {
    id: 1,
    assetId: "ASS-EBK-8990",
    type: "public",
    userName: "Dr. Ahmad Hassan",
    date: "19-Nov-2025 1:30 AM",
    sales: 22000,
    orders: 1200,
    customers: 1200,
    likes: 1100,
    shares: 320,
    rating: 4.8,
    ratingPoints: 33,
    isFeatured: "featured",
    isExclusive: "exclusive",
    price: 100,
    paymentType: "paid",
    bargain: "discount",
    discountPercentage: 25,
    imageUrl: "/images/article-ebook.png",
  },
];

export const vAssetEventsData = [
  {
    id: 1,
    assetId: "ASS-EVT-73",
    type: "Public",
    userName: "Dr. Ahmad Hassan",
    date: "19-Nov-2025 1:30 AM",
    sales: 22000,
    orders: 1200,
    customers: 1200,
    likes: 1100,
    shares: 320,
    rating: 4.8,
    ratingPoints: 33,
    price: 125,
    isFeatured: "featured",
    paymentType: "paid",
    eventHowSoon: "coming",
    country: "egypt",
    eventDuration: 24,
    tickets: "150",
    imageUrl: "/images/article-event-conference.png",
  },
];

export const vAssetWebinarData = [
  {
    id: 1,
    assetId: "ASS-WBR-128",
    type: "public",
    userName: "Dr. Ahmad Hassan",
    date: "19-Nov-2025 1:30 AM",
    sales: 22000,
    orders: 75,
    customers: 1200,
    likes: 1100,
    shares: 320,
    rating: 0,
    ratingPoints: 0,
    isFeatured: "featured",
    price: 125,
    paymentType: "paid",
    eventHowSoon: "coming",
    eventDuration: 5,
    tickets: "150",
    imageUrl: "/images/article-webinar-online.png",
  },
];

export const vAssetExpertsData = [
  {
    id: 1,
    assetId: "ASS-CST-8990",
    type: "public",
    userName: "Dr. Ahmad Hassan",
    date: "19-Nov-2025 1:30 AM",
    sales: 1200,
    orders: 75,
    customers: 575,
    likes: 1100,
    shares: 320,
    rating: 0,
    ratingPoints: 0,
    isFeatured: "featured",
    isExclusive: "exclusive",
    price: 125,
    paymentType: "paid",
    eventDuration: 5,
    imageUrl: "/images/article-experts-consultation.png",
  },
];

export const vAssetSponsorshipData = [
  {
    id: 1,
    assetId: "ASS-SPN-8990",
    type: "public",
    userName: "Dr. Ahmad Hassan",
    date: "19-Nov-2025 1:30 AM",
    sales: 1200,
    orders: 75,
    customers: 575,
    likes: 1100,
    shares: 320,
    rating: 0,
    ratingPoints: 0,
    isFeatured: "featured",
    isExclusive: "exclusive",
    price: 125,
    paymentType: "paid",
    bargain: "regular",
    imageUrl: "/images/article-sponsorship-marketing-graph.png",
  },
];

export const vAssetsJobsLancerData = [
  {
    id: 1,
    assetId: "ASS-SRV-122",
    title:
      "Lance Job Page for sale, jobs for enrollment. V-Verse Lancer Asset.",
    type: "public",
    userName: "Dr. Ahmad Hassan",
    date: "19-Nov-2025 1:30 AM",
    sales: 22200,
    orders: 1200,
    customers: 1200,
    likes: 110000,
    shares: 32000,
    rating: 4.8,
    ratingPoints: 2000,
    isFeatured: "featured",
    isExclusive: "exclusive",
    price: 40,
    deliveryTime: 72,
    positionDuration: "fulltime",
    salaryPaymentTime: "monthly",
    monthlySalary: 1250,
    imageUrl: "/images/article-laptop-typing.png",
  },
];

// video player backend data test
export const videoPlayerData = [
  {
    id: 1,
    title: "New video",
    videoUrl:
      "https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-576p.mp4",
    channel: "Plyr Demo",
    user: "Plyr User",
    poster: "/images/article-laptop-typing.png",
    // chapters: [
    //   {
    //     title: "Introduction",
    //     url: "https://example.com/intro.vtt",
    //   },
    //   {
    //     title: "Conclusion",
    //     url: "https://example.com/conclusion.vtt",
    //   },
    // ],
  },
];

// Personal profile backend test data
